name: Test MCP Tutorial

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10"]
      fail-fast: false

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest nbval jupyter pytest-xdist
    
    - name: Create test directories
      run: |
        mkdir -p examples/weather_mcp/tests
        mkdir -p examples/database_manager/tests
        mkdir -p examples/file_processor/tests
        touch examples/weather_mcp/tests/__init__.py
        touch examples/database_manager/tests/__init__.py
        touch examples/file_processor/tests/__init__.py
    
    - name: Test notebooks
      run: |
        pytest --nbval-lax notebooks/ -v
    
    - name: Test example projects
      run: |
        for d in examples/*/; do
          if [ -f "$d/requirements.txt" ]; then
            cd "$d"
            pip install -r requirements.txt
            pytest -v
            cd ../..
          fi
        done 